# from GitHub, overriding the name and specifying a specific tag
- src: https://github.com/geerlingguy/ansible-role-docker.git
  version: master
  name: geerlingguy.docker

- src: capitanh.openldap-ansible-role
  version: master
  name: openldap